name: Test version

on:
    workflow_dispatch:

jobs:
    version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: version
              id: version
              run: |
                SHORT_SHA=$(echo $GITHUB_SHA | cut -c -7)
                echo "sha=$SHORT_SHA" >> $GITHUB_OUTPUT
                echo sha=[$SHORT_SHA]
                VERSION=$(head -n 1 VERSION)
                VERSION=`echo ${VERSION} | sed -e "s/[\r\n]\+//g"`
                echo "version=$VERSION" >> $GITHUB_OUTPUT
                echo version=[$VERSION-$SHORT_SHA]
      